class ActionSequence:
    """Represents a sequence of test actions from a session."""
    
    def __init__(self, session_id, actions):
        self.session_id = session_id
        self.actions = actions
        
    def get_actions_by_type(self, action_type):
        """Filter actions by type."""
        return [a for a in self.actions if a.get('actionType') == action_type]
    
    def get_navigation_sequence(self):
        """Get the sequence of page navigations."""
        navigations = self.get_actions_by_type('NAVIGATE')
        return [(n.get('url'), n.get('pageTitle')) for n in navigations]
    
    def get_action_count(self):
        """Get the total number of actions."""
        return len(self.actions)
    
    def get_unique_pages(self):
        """Get unique pages visited."""
        return list(set(a.get('url') for a in self.actions if a.get('url')))

class TestSuggestion:
    """Represents a testing suggestion generated by the AI."""
    
    def __init__(self, title, description, suggestion_type, priority, suggested_action=None):
        self.title = title
        self.description = description
        self.suggestion_type = suggestion_type  # EDGE_CASE, TEST_DATA, VALIDATION, etc.
        self.priority = priority  # HIGH, MEDIUM, LOW
        self.suggested_action = suggested_action
        
    def to_dict(self):
        """Convert to dictionary for API response."""
        return {
            "title": self.title,
            "description": self.description,
            "suggestionType": self.suggestion_type,
            "priority": self.priority,
            "suggestedAction": self.suggested_action
        }
